apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-6inq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-6inq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-6inq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-6inq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-6inq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-etkq-tenant/rhtap-demo-app/hacbs-test-project-6inq@sha256:95cfe32358d97ac3f64b6b84ffe7187cdb115d31ee7357f23c141a959d3d19cf
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
