apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-6inq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-etkq-tenant/rhtap-demo-app/hacbs-test-project-6inq@sha256:4390b8950e878aa309d88408c7a16098ba249433406387d7df73c781b7c3bfa9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
